# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28f6f2d98529d217b32fb02b80f1aa252bbe5aadce6010b6917f08579ed11379ff89f33f8c9368371961307184bad687c9b9b36a4ba2f506ce78e44e30321114

test:
  secret_key_base: 3de552ee24e8f0fe7c4ffc5f88ef16f9152615abd8373fb50d7454ace2ec296723fcca55ce9586fde06dafd6593ed1427845e9929501cef29e45267485edda81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
